// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using KSP;
using UnityEngine;
using KSPPluginFramework;

namespace TestFlightCore
{
    public class Settings : ConfigNodeStorage
    {
        public Settings(String FilePath) : base(FilePath) {
        }

        [Persistent]
        public double minTimeBetweenDataPoll;
        [Persistent]
        public double minTimeBetweenFailurePoll;
        [Persistent]
        public bool processAllVessels;
        [Persistent]
        public double flightDataMultiplier;
        [Persistent]
        public double flightDataEngineerMultiplier;
        [Persistent]
        public double globalReliabilityModifier;
        [Persistent]
        public double masterStatusUpdateFrequency;
        [Persistent] public bool displaySettingsWindow;
        [Persistent] public bool enableHUD;
    }
}

