// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using KSP;
using UnityEngine;
using KSPPluginFramework;

namespace TestFlightCore
{
    public class Styles
    {
        internal static GUIStyle panelStyle;

        internal static GUIStyle textStyleCritical;
        internal static GUIStyle textStyleWarning;
        internal static GUIStyle textStyleSafe;
        internal static GUIStyle textStyleStandard;

        public static void Init()
        {
            panelStyle = new GUIStyle(SkinsLibrary.DefKSPSkin.window);
//            panelStyle.border = new RectOffset(6, 6, 6, 6);
//            panelStyle.padding = new RectOffset(8, 3, 7, 0);

            textStyleStandard = new GUIStyle(SkinsLibrary.DefUnitySkin.label);
            textStyleStandard.fontSize = 12;
            textStyleStandard.alignment = TextAnchor.MiddleLeft;
            textStyleStandard.normal.textColor = new Color(253, 246, 227);
            textStyleStandard.wordWrap = false;

            textStyleSafe = new GUIStyle(textStyleStandard);
            textStyleSafe.normal.textColor = new Color32(133, 153, 0, 255);        
            
            textStyleWarning = new GUIStyle(textStyleStandard);
            textStyleWarning.normal.textColor = new Color32(203, 75, 22, 255);        
            
            textStyleCritical = new GUIStyle(textStyleStandard);
            textStyleCritical.normal.textColor = new Color32(220, 50, 47, 255);        

            GUISkin skinDefault = SkinsLibrary.CopySkin(SkinsLibrary.DefSkinType.Unity);
            skinDefault.font = SkinsLibrary.DefUnitySkin.font;
//            skinDefault.window = panelStyle;
            skinDefault.label = new GUIStyle(textStyleStandard);
            SkinsLibrary.AddSkin("Default", skinDefault);
        }
    }
}

